packages:
  - '.'
autoInstallPeers: false
allowBuilds:
  argon2: true
  better-sqlite3: true
  esbuild: true
minimumReleaseAgeExclude:
  - ajo@0.1.35
  - ajo-kit@0.3.0
  - ajo-kit-auth@0.6.0
  - ajo-kit-mail@0.3.0
  - ajo-cloves@0.1.2
  - ajo-ui@0.1.2
  - ajo-ui-playa@0.1.2
  - ajo-kit-server@0.1.0
  - ajo-engine@0.1.0
  - ajo-engine-compiler@0.1.0
