packages:
  - 'packages/*'
autoInstallPeers: false
allowBuilds:
  argon2: true
  better-sqlite3@13.0.3: false
  esbuild: true
minimumReleaseAgeExclude:
  - ajo@0.2.0
  - ajo-engine@0.2.0
  - ajo-engine-compiler@0.2.0
versioning:
  ignore:
    - ajo-kit-demo
  changelog:
    storage: repository
overrides:
  ajo-kit-server: file:.tarballs/ajo-kit-server-0.3.0.tgz
