import type {
	AccordionArgs,
	AccordionContentArgs,
	AccordionItemArgs,
	AccordionMultipleArgs,
	AccordionSingleArgs,
	AccordionTriggerArgs,
	CarouselArgs,
	CarouselButtonArgs,
	CarouselContentArgs,
	CarouselItemArgs,
	ChartContainerArgs,
	ChartLegendArgs,
	ChartLegendContentArgs,
	ChartPieArgs,
	ChartPlotArgs,
	ChartTooltipArgs,
	ChartTooltipContentArgs,
	CheckboxGroupArgs,
	CheckboxGroupItemArgs,
	CollapsibleArgs,
	CollapsibleContentArgs,
	CollapsibleTriggerArgs,
	InputGroupAddonArgs,
	InputGroupArgs,
	InputGroupButtonArgs,
	InputGroupInputArgs,
	InputGroupTextArgs,
	InputGroupTextareaArgs,
	InputOTPArgs,
	InputOTPGroupArgs,
	InputOTPSeparatorArgs,
	InputOTPSlotArgs,
	MessageScrollerArgs,
	MessageScrollerButtonArgs,
	MessageScrollerContentArgs,
	MessageScrollerItemArgs,
	MessageScrollerViewportArgs,
	RadioGroupArgs,
	RadioGroupItemArgs,
	ResizableHandleArgs,
	ResizablePanelArgs,
	ResizablePanelGroupArgs,
	SliderArgs,
	TabsArgs,
	TabsContentArgs,
	TabsListArgs,
	TabsTriggerArgs,
	ToggleGroupArgs,
	ToggleGroupItemArgs,
	ToggleGroupMultipleArgs,
	ToggleGroupSingleArgs,
} from '../src/ui'
import {
	emptyMediaVariants,
	navigationMenuTriggerVariants,
	sidebarMenuActionVariants,
	sidebarMenuButtonVariants,
} from '../src/ui'

type StringClass<T extends { class?: string }> = T

/** Compile-only contract: themed DOM parts keep the theme's string class API. */
export type ThemeClassContracts = [
	StringClass<AccordionArgs>,
	StringClass<AccordionContentArgs>,
	StringClass<AccordionItemArgs>,
	StringClass<AccordionMultipleArgs>,
	StringClass<AccordionSingleArgs>,
	StringClass<AccordionTriggerArgs>,
	StringClass<CarouselArgs>,
	StringClass<CarouselButtonArgs>,
	StringClass<CarouselContentArgs>,
	StringClass<CarouselItemArgs>,
	StringClass<ChartContainerArgs>,
	StringClass<ChartLegendArgs>,
	StringClass<ChartLegendContentArgs>,
	StringClass<ChartPieArgs>,
	StringClass<ChartPlotArgs>,
	StringClass<ChartTooltipArgs>,
	StringClass<ChartTooltipContentArgs>,
	StringClass<CheckboxGroupArgs>,
	StringClass<CheckboxGroupItemArgs>,
	StringClass<CollapsibleArgs>,
	StringClass<CollapsibleContentArgs>,
	StringClass<CollapsibleTriggerArgs>,
	StringClass<InputGroupAddonArgs>,
	StringClass<InputGroupArgs>,
	StringClass<InputGroupButtonArgs>,
	StringClass<InputGroupInputArgs>,
	StringClass<InputGroupTextArgs>,
	StringClass<InputGroupTextareaArgs>,
	StringClass<InputOTPArgs>,
	StringClass<InputOTPGroupArgs>,
	StringClass<InputOTPSeparatorArgs>,
	StringClass<InputOTPSlotArgs>,
	StringClass<MessageScrollerArgs>,
	StringClass<MessageScrollerButtonArgs>,
	StringClass<MessageScrollerContentArgs>,
	StringClass<MessageScrollerItemArgs>,
	StringClass<MessageScrollerViewportArgs>,
	StringClass<RadioGroupArgs>,
	StringClass<RadioGroupItemArgs>,
	StringClass<ResizableHandleArgs>,
	StringClass<ResizablePanelArgs>,
	StringClass<ResizablePanelGroupArgs>,
	StringClass<SliderArgs>,
	StringClass<TabsArgs>,
	StringClass<TabsContentArgs>,
	StringClass<TabsListArgs>,
	StringClass<TabsTriggerArgs>,
	StringClass<ToggleGroupArgs>,
	StringClass<ToggleGroupItemArgs>,
	StringClass<ToggleGroupMultipleArgs>,
	StringClass<ToggleGroupSingleArgs>,
]

/** Compile-only contract for the deliberate public variant-helper surface. */
export const publicVariantSurface = [
	emptyMediaVariants({ variant: 'icon' }),
	navigationMenuTriggerVariants({ class: 'group' }),
	sidebarMenuActionVariants({ showOnHover: true }),
	sidebarMenuButtonVariants({ size: 'lg', variant: 'outline' }),
]
