import { expect, test } from '@playwright/test'

test('a new account can keep notes live across tabs, preview its email and sign out', async ({ page, context }) => {
	const errors: string[] = []
	context.on('weberror', event => errors.push(event.error().message))
	context.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
	await page.goto('/')
	await page.getByRole('link', { name: 'Create account', exact: true }).click()
	await page.getByLabel('Name', { exact: true }).fill('Reader')
	await page.getByLabel('Email', { exact: true }).fill('browser@example.test')
	await page.getByLabel('Password', { exact: true }).fill('a-long-test-password')
	await page.getByLabel('Confirm password').fill('a-long-test-password')
	await page.getByRole('button', { name: 'Create account', exact: true }).click()
	await expect(page).toHaveURL(/\/login$/)
	await page.getByLabel('Email', { exact: true }).fill('browser@example.test')
	await page.getByLabel('Password', { exact: true }).fill('a-long-test-password')
	await page.getByRole('button', { name: 'Sign in', exact: true }).click()
	await expect(page).toHaveURL(/\/notes$/)
	const second = await context.newPage()
	await second.goto('/notes')
	await page.getByLabel('New note').fill('Shared across my tabs')
	await page.getByRole('button', { name: 'Add', exact: true }).click()
	await expect(page.getByText('Shared across my tabs', { exact: true })).toBeVisible()
	await expect(second.getByText('Shared across my tabs', { exact: true })).toBeVisible()
	await expect(page.getByRole('button', { name: 'Email my notes' })).toBeDisabled()
	await page.getByRole('button', { name: 'Send verification email' }).click()
	await page.getByRole('link', { name: 'Verify this email', exact: true }).click()
	await expect(page.getByRole('heading', { name: 'Email verified', exact: true })).toBeVisible()
	await page.getByRole('link', { name: 'Return to my notes' }).click()
	await page.getByRole('button', { name: 'Email my notes' }).click()
	await expect(page.getByText('Message captured below. No email was sent.')).toBeVisible()
	await expect(page.getByText('• Shared across my tabs', { exact: true })).toBeVisible()
	await page.getByRole('button', { name: 'Delete note: Shared across my tabs' }).click()
	await expect(second.getByText('Shared across my tabs', { exact: true })).toHaveCount(0)
	await page.getByRole('button', { name: 'Sign out' }).click()
	await expect(page).toHaveURL(/\/login$/)
	await second.reload()
	await expect(second).toHaveURL(/\/login$/)
	expect(errors).toEqual([])
})
