import type { Children, Component } from 'ajo'
import type { Params } from 'navaid'
import type { Request, Response, Middleware } from 'polka'
/** Polka request, response, and middleware types used by route modules. */
export type { Request, Response, Middleware }
/** Document head payload returned by route head loaders. */
export type { Head } from './head'
import type { Head } from './head'
import type { Timing } from './timing'

// Route errors with HTTP status codes

/** HTTP-aware error serialized by loaders, actions, and API handlers. */
export class Failure extends Error {

	constructor(public status: number, message: string) {
		super(message)
	}

	toJSON() {
		return {
			message: mask(this.status, this.message),
			status: this.status,
			...(!production() && import.meta.env.DEV && { stack: this.stack })
		}
	}
}

/** 404 error for missing routes or resources. */
export class Missing extends Failure {
	constructor(message = 'Page not found') {
		super(404, message)
	}
}

/** 403 error for authenticated users without enough access. */
export class Forbidden extends Failure {
	constructor(message = 'Access denied') {
		super(403, message)
	}
}

/** 401 error for requests that need authentication. */
export class Denied extends Failure {
	constructor(message = 'Authentication required') {
		super(401, message)
	}
}

/** Field-level validation errors keyed by form field name. */
export type Fields = Record<string, string[] | undefined>

/** Client action error shape exposed by action() state. */
export type Issue = {
	status: number
	message: string
	fields?: Fields
}

/** 400 validation error carrying field-level messages. */
export class Invalid extends Failure {
	constructor(public fields: Fields, message = 'Validation failed') {
		super(400, message)
	}
	toJSON() {
		return {
			message: mask(this.status, this.message),
			status: this.status,
			fields: this.fields,
			...(!production() && import.meta.env.DEV && { stack: this.stack })
		}
	}
}

const production = () => process.env.NODE_ENV === 'production'
const mask = (status: number, message: string) =>
	production() && status >= 500 ? 'Internal Server Error' : message
const config = (message: string) => {
	if (production()) console.error(`[security] ${message}`)
	return new Failure(500, message)
}
const code = (error: unknown) => {
	if (!error || typeof error !== 'object') return 500

	const value = (error as { status?: unknown }).status ?? (error as { statusCode?: unknown }).statusCode

	return Number.isInteger(value) && (value as number) >= 400 && (value as number) <= 599
		? value as number
		: 500
}
const message = (error: unknown, status: number) => {
	if (status === 413) return 'Content Too Large'
	if (error instanceof Error && error.message) return error.message
	return status < 500 ? 'Request failed' : 'Unknown error'
}

/** Converts any thrown value into a framework Failure. */
export function normalize(error: unknown): Failure {
	if (error instanceof Failure) return error
	const status = code(error)
	return new Failure(status, message(error, status))
}

// Route path utilities

/** Returns route ancestor keys from outermost to innermost. */
export const ancestors = (segments: string[]) => segments.map((_, i) => segments.slice(0, i + 1).join('/'))

// Loader data types

/** Data object returned by one loader. */
export type Entry = Record<string, unknown>

/** Ordered loader data for layouts followed by the page. */
export type Data = Entry[]

/** Server payload containing head data followed by loader entries. */
export type Payload = [Head, ...Data]

/** Reads merged data from ancestor loaders. */
export type Parent = () => Promise<Entry>

// Route module types

/** Runtime shape of a route page or layout module. */
export type Module = {
	default: Component
	/** Receives loading=true while client navigation is pending. */
	pending?: boolean
}

/** Lazy module loader generated by Vite route globs. */
export type Loader = () => Promise<Module>

/** Compiled route page metadata used by the client and server routers. */
export type Page = {
	loader: Loader
	segments: string[]
	pattern?: string
	params?: Params
}

/** Client route state produced by SSR, JSON loads, and navigation. */
export interface State {
	url: string
	params: Params
	data: Data
	loading: boolean
	error?: Failure
	head?: Head
	hash?: string
	topics?: string[]
	versions?: Record<string, number>
}

/** State and commands returned by the client action() helper. */
export type Action<T> = {
	loading: boolean
	data?: T
	error?: Issue
	submit: (event: SubmitEvent) => void
	invoke: (body?: unknown) => Promise<T | undefined>
	reset: () => void
}

// Page and layout args

/** Props passed to page components. */
export type Props<T = Entry> = {
	params: Params
	data?: T
	loading: boolean
	error?: Failure
}

/** Props passed to layout components, including children. */
export type Frame<T = Entry> = Props<T> & {
	children: Children
}

// Navigation helper

/** Pushes a browser URL and asks the client router to navigate. */
export const navigate = (to: string) => {
	globalThis.history?.pushState({}, '', to)
	globalThis.dispatchEvent?.(new CustomEvent('ajo:navigate'))
}

// Request helpers

/** Returns true when a request expects JSON route/action data. */
export const ajax = (req: Request) => !!req.headers.accept?.includes('application/json')
/** Returns true when a request targets the /api route namespace. */
export const api = (req: Request) => req.path.startsWith('/api/')

const enabled = (value: string | undefined) => value === '1' || value?.toLowerCase() === 'true'
const proxy = () => enabled(process.env.TRUST_PROXY)

const first = (value: string | string[] | undefined) =>
	Array.isArray(value) ? value[0] : value

const address = (value: string) => {
	const raw = value.trim().replace(/^\[/, '').replace(/\]$/, '').replace(/^::ffff:/, '')
	return raw === '::1' || raw === '127.0.0.1' ? 'localhost' : raw
}

const ipv4 = (value: string) => {
	const parts = value.split('.')
	return parts.length === 4 && parts.every(part => {
		if (!/^\d{1,3}$/.test(part)) return false
		const number = Number(part)
		return number >= 0 && number <= 255
	})
}

const ipv6 = (value: string) =>
	value.includes(':') && /^[0-9a-f:.]+$/i.test(value)

const local = (host: string) => {
	try {
		return address(new URL(`http://${host}`).hostname) === 'localhost'
	} catch {
		return false
	}
}

const forwarded = (header: string | string[] | undefined) => {
	const value = first(header)
	if (!value) return

	const addr = address(value.split(',')[0])
	if (addr === 'localhost' || ipv4(addr) || ipv6(addr)) return addr
}

/** Resolves the client IP, honoring TRUST_PROXY for forwarded headers. */
export const ip = (req: Request) => {
	const raw = proxy()
		? forwarded(req.headers['x-forwarded-for']) ?? req.socket?.remoteAddress
		: req.socket?.remoteAddress

	return raw ? address(raw) : 'unknown'
}

/** Resolves the trusted app origin from APP_URL or the request host. */
export const origin = (req: Request) => {
	const configured = process.env.APP_URL

	if (configured) {
		try {
			const url = new URL(configured)
			if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new Error()
			return url.origin
		} catch {
			throw config('Invalid APP_URL')
		}
	}

	const host = req.headers.host
	if (!host) throw new Failure(400, 'Missing Host header')

	if (production() && !local(host)) {
		throw config('APP_URL is required in production')
	}

	const forwarded = first(req.headers['x-forwarded-proto'])?.split(',')[0]?.trim()
	const protocol = proxy() && (forwarded === 'http' || forwarded === 'https') ? forwarded : 'http'

	try {
		return new URL(`${protocol}://${host}`).origin
	} catch {
		throw new Failure(400, 'Invalid Host header')
	}
}

// Auth types

/** Authenticated user shape attached to requests by auth middleware. */
export interface User {
	id: number
	roles?: string[]
	[key: string]: unknown
}

// Request extensions for polka

declare module 'polka' {
	interface Request {
		user?: User
		session?: { id: string }
		token?: { id: string; abilities: string[] }
		topics?: Set<string>
		track?: (topic: string | string[]) => void
		verifyLive?: () => Promise<boolean>
		timing?: Timing
		revalidate?: () => Promise<Payload>
		head?: Head
		entries?: Data
	}
}

// Deferred promises for parallel loader execution

/** Internal parent/deferred link used to run loaders in parallel. */
export type Link = {
	parent: Parent
	deferred: { promise: Promise<Entry>; resolve: (value: Entry) => void; reject: (error: Error) => void }
}

/** Builds parent/deferred links for a loader chain. */
export function links(count: number): Link[] {

	const chain: Link[] = []

	for (let depth = 0; depth < count; depth++) {

		let resolve!: (value: Entry) => void
		let reject!: (error: Error) => void

		const promise = new Promise<Entry>((res, rej) => {
			resolve = res
			reject = rej
		})

		const parent = async () =>
			Object.assign({}, ...await Promise.all(chain.slice(0, depth).map(link => link.deferred.promise)))

		chain.push({ parent, deferred: { promise, resolve, reject } })
	}

	return chain
}

// Formatting

/** Formats an ISO date for the current locale with compact defaults. */
export const date = (iso: string, options?: Intl.DateTimeFormatOptions) =>
	new Date(iso).toLocaleDateString(undefined, options ?? { month: 'short', day: 'numeric', year: 'numeric' })
