import type { Children, Component } from 'ajo'
import { env } from 'ajo-kit/platform'
import type { Params } from 'navaid'
import type { Request, Reply, Value } from './http'
import type { Head } from './head'
import type { Kysely } from './database'

/** Host-neutral response accumulator used by route modules. */
export type Response = Reply

// Route errors with HTTP status codes

/** HTTP-aware error serialized by loaders, actions, and API handlers. */
export class Failure extends Error {

	constructor(public status: number, message: string) {
		super(message)
	}

	toJSON() {
		return {
			message: mask(this.status, this.message),
			status: this.status,
			...(!production() && import.meta.env.DEV && { stack: this.stack })
		}
	}
}

/** 404 error for missing routes or resources. */
export class Missing extends Failure {
	constructor(message = 'Page not found') {
		super(404, message)
	}
}

/** 403 error for authenticated users without enough access. */
export class Forbidden extends Failure {
	constructor(message = 'Access denied') {
		super(403, message)
	}
}

/** 401 error for requests that need authentication. */
export class Denied extends Failure {
	constructor(message = 'Authentication required') {
		super(401, message)
	}
}

/** Field-level validation errors keyed by form field name. */
export type Fields = Record<string, string[] | undefined>

/** Client action error shape exposed by action() state. */
export type Issue = {
	status: number
	message: string
	fields?: Fields
}

/** 400 validation error carrying field-level messages. */
export class Invalid extends Failure {
	constructor(public fields: Fields, message = 'Validation failed') {
		super(400, message)
	}
	toJSON() {
		return { ...super.toJSON(), fields: this.fields }
	}
}

/** Returns true when the current host runs in production mode. */
export const production = () => env('NODE_ENV') === 'production'
const mask = (status: number, message: string) =>
	production() && status >= 500 ? 'Internal Server Error' : message
const config = (message: string) => {
	if (production()) console.error(`[security] ${message}`)
	return new Failure(500, message)
}
const code = (error: unknown) => {
	if (!error || typeof error !== 'object') return 500

	const value = (error as { status?: unknown }).status ?? (error as { statusCode?: unknown }).statusCode

	return Number.isInteger(value) && (value as number) >= 400 && (value as number) <= 599
		? value as number
		: 500
}
const message = (error: unknown, status: number) => {
	if (status === 413) return 'Content Too Large'
	if (error instanceof Error && error.message) return error.message
	return status < 500 ? 'Request failed' : 'Unknown error'
}

/** Converts any thrown value into a framework Failure. */
export function normalize(error: unknown): Failure {
	if (error instanceof Failure) return error
	const status = code(error)
	return new Failure(status, message(error, status))
}

/** Returns route ancestor keys from outermost to innermost. */
export const ancestors = (segments: string[]) => segments.map((_, i) => segments.slice(0, i + 1).join('/'))

// Loader data types

/** Data object returned by one loader. */
export type Entry = Record<string, unknown>

/** Ordered loader data for layouts followed by the page. */
export type Data = Entry[]

/** Reads merged data from ancestor loaders. */
export type Parent = () => Promise<Entry>

/** Per-action commands whose effects are included in that action's response. */
export type ActionContext = {
	/** Broadcasts changed topics and records them for this action response. */
	emit: (topic: string | string[]) => void
}

// Route module types

/** Runtime shape of a route page or layout module. */
export type Module = {
	default: Component
	/** Receives loading=true while client navigation is pending. */
	pending?: boolean
}

/** Lazy module loader generated by Vite route globs. */
export type Loader = () => Promise<Module>

/** Compiled route page metadata used by the client and server routers. */
export type Page = {
	loader: Loader
	segments: string[]
	pattern?: string
	params?: Params
}

/** Client route state produced by SSR, JSON loads, and navigation. */
export interface State {
	url: string
	params: Params
	data: Data
	loading: boolean
	error?: Issue
	head?: Head
	hash?: string
	topics?: string[]
	versions?: Record<string, number>
	/** Server-declared cache scope: the partition the client caches this under. */
	scope?: string
}

/** State and commands returned by the client action() helper. */
export type Action<T> = {
	loading: boolean
	data?: T
	error?: Issue
	submit: (event: SubmitEvent) => void
	invoke: (body?: unknown) => Promise<T | undefined>
	/** Aborts any in-flight request and clears loading, data, and error state. */
	reset: () => void
}

// Page and layout args

/** Route page component args. */
export type PageArgs<T = Entry> = {
	params: Params
	data?: T
	loading: boolean
	error?: Issue
}

/** Route layout component args, including children. */
export type LayoutArgs<T = Entry> = PageArgs<T> & {
	children: Children
}

/** Pushes a browser URL and asks the client router to navigate. */
export const navigate = (to: string) => {
	globalThis.history?.pushState({}, '', to)
	globalThis.dispatchEvent?.(new CustomEvent('ajo:navigate'))
}

// Request helpers

/** Returns true when a request expects JSON route/action data. */
export const ajax = (req: Request) => {
	const accept = req.headers.accept
	return Array.isArray(accept) ? accept.some(value => value.includes('application/json')) : !!accept?.includes('application/json')
}
/** Returns true when a request targets the /api route namespace. */
export const api = (req: Request) => req.path.startsWith('/api/')

const enabled = (value: string | undefined) => value === '1' || value?.toLowerCase() === 'true'
const proxy = () => enabled(env('TRUST_PROXY'))

/** Returns the first value of a repeated header or query field. */
export const first = (value: string | string[] | undefined) =>
	Array.isArray(value) ? value[0] : value

// The one trusted proxy appends its entry, so only the last forwarded hop is its own.
const hop = (value: string | string[] | undefined) =>
	(Array.isArray(value) ? value.at(-1) : value)?.split(',').at(-1)?.trim()

const address = (value: string) => {
	const raw = value.trim().replace(/^\[/, '').replace(/\]$/, '').replace(/^::ffff:/, '')
	return raw === '::1' || raw === '127.0.0.1' ? 'localhost' : raw
}

const ipv4 = (value: string) => {
	const parts = value.split('.')
	return parts.length === 4 && parts.every(part => {
		if (!/^\d{1,3}$/.test(part)) return false
		const number = Number(part)
		return number >= 0 && number <= 255
	})
}

const ipv6 = (value: string) =>
	value.includes(':') && /^[0-9a-f:.]+$/i.test(value)

const local = (host: string) => {
	try {
		return address(new URL(`http://${host}`).hostname) === 'localhost'
	} catch {
		return false
	}
}

const forwarded = (header: string | string[] | undefined) => {
	const value = hop(header)
	if (!value) return

	const addr = address(value)
	if (addr === 'localhost' || ipv4(addr) || ipv6(addr)) return addr
}

/** Resolves the client IP, honoring TRUST_PROXY with the last forwarded IP. */
export const ip = (req: Request) => {
	const raw = proxy()
		? forwarded(req.headers['x-forwarded-for']) ?? req.remoteAddress
		: req.remoteAddress

	return raw ? address(raw) : 'unknown'
}

type OriginReader = (path: string, options: { maxBytes: number }) => string
let originReader: OriginReader | undefined

/** Registers the host-owned origin manifest reader; the engine entry passes runtime:fs readText. */
export const setOriginReader = (reader: OriginReader | undefined) => {
	originReader = reader
}

const domain = /^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/

// The host writes this manifest root-owned and read-only; any failure refuses the request.
const manifest = (host: string) => {
	try {
		const value = JSON.parse(originReader!('/ajo/origin/origins.json', { maxBytes: 4096 }))
		if (value?.schema !== 'ajo.origins/v1' || !Array.isArray(value.origins) ||
			!value.origins.every((item: unknown) => typeof item === 'string')) throw new Error()
		return (value.origins as string[]).map(item => new URL(item)).find(url => url.host === host)?.origin
	} catch {
		throw config('Invalid origin manifest')
	}
}

const requestHost = (req: Request) => {
	const value = req.headers.host
	if (typeof value !== 'string' || !value || value !== value.trim() || /[,\s\/@?#]/.test(value))
		throw new Failure(400, 'Invalid Host header')
	try {
		const url = new URL(`https://${value}`)
		const hostname = address(url.hostname)
		if (url.host !== value.toLowerCase() || (!domain.test(hostname) && !ipv4(hostname) && !ipv6(hostname)) ||
			hostname.includes('..')) throw new Error()
		return url.host
	} catch {
		throw new Failure(400, 'Invalid Host header')
	}
}

/** Resolves the canonical application origin from APP_URL or the local request host. */
export const origin = (req: Request) => {
	const configured = env('APP_URL')

	if (configured) {
		try {
			const url = new URL(configured)
			if (url.protocol !== 'http:' && url.protocol !== 'https:') throw new Error()
			return url.origin
		} catch {
			throw config('Invalid APP_URL')
		}
	}

	const host = first(req.headers.host)
	if (!host) throw new Failure(400, 'Missing Host header')

	if (production() && !local(host)) {
		throw config('APP_URL is required in production')
	}

	const forwarded = hop(req.headers['x-forwarded-proto'])
	const protocol = proxy() && (forwarded === 'http' || forwarded === 'https') ? forwarded : 'http'

	try {
		return new URL(`${protocol}://${host}`).origin
	} catch {
		throw new Failure(400, 'Invalid Host header')
	}
}

/**
 * Resolves the origin of this exact request after admitting its direct Host.
 * With AJO_ORIGINS_FILE set, admitted Hosts come only from the host-owned origins manifest.
 */
export const requestOrigin = (req: Request) => {
	const host = requestHost(req)
	const matched = env('AJO_ORIGINS_FILE') !== undefined
		? manifest(host)
		: [origin(req)].find(value => new URL(value).host === host)
	if (!matched) throw new Failure(421, 'Misdirected Request')
	return matched
}

/** Engine startup hook run after migrations and before request handling. */
export type Bootstrap<Database = any> = (context: { db: Kysely<Database> }) => Promise<void>

// Auth types

/** Authenticated user shape attached to requests by auth middleware. */
export interface User {
	id: number
	roles?: string[]
	abilities?: string[]
	[key: string]: unknown
}

// Request extensions

declare module './http' {
	interface Request {
		user?: User
		session?: { id: string }
		/** Bearer identity; a non-null subject requires subject-aware authorization. */
		token?: { id: string; abilities: string[]; subject: string | null }
		/** Cache scope override set by auth middleware; the kit derives one otherwise. */
		scope?: string
		topics?: Set<string>
		track?: (topic: string | string[]) => void
	}
}

// Formatting

/**
 * The frozen SSR locale. SSR output is deterministic en-US/UTC; locale- or
 * timezone-sensitive text that must follow the viewer belongs in client-side
 * post-hydration rendering.
 */
export const locale = 'en-US'

/** Formats an ISO date in the frozen SSR locale with compact defaults. */
export const date = (iso: string, options?: Intl.DateTimeFormatOptions) =>
	new Date(iso).toLocaleDateString(locale, options ?? { month: 'short', day: 'numeric', year: 'numeric' })

// Response headers

const https = () => {
	if (!production()) return false

	const origin = env('APP_URL')
	if (!origin) return false

	try {
		return new URL(origin).protocol === 'https:'
	} catch {
		return false
	}
}

/** Security headers shared by dynamic SSR responses and static assets. */
export const security = () => ({
	'X-Content-Type-Options': 'nosniff',
	'Referrer-Policy': 'strict-origin-when-cross-origin',
	'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
	'Content-Security-Policy': "frame-ancestors 'none'",
	...(https() && { 'Strict-Transport-Security': 'max-age=31536000' }),
})

/** Writes headers, optionally preserving values already set downstream. */
export const set = (
	res: { setHeader(key: string, value: Value): unknown; hasHeader(key: string): boolean },
	values: Record<string, Value>,
	missing = false,
) => {
	for (const [key, value] of Object.entries(values)) {
		if (!missing || !res.hasHeader(key)) res.setHeader(key, value)
	}
}

// Request timing

const disabled = new Set(['', '0', 'false', 'off'])

const timed = () => {
	const value = env('AJO_TIMING')
	return !!value && !disabled.has(value.toLowerCase())
}

const round = (value: number) => Math.round(value * 10) / 10

/** Optional request phase timings measured in milliseconds from a monotonic clock. */
export type Timing = {
	start: number
	loader?: number
	render?: number
}

/** Completed request timing data used for headers and diagnostic logs. */
export type Result = Timing & {
	total: number
	status: number
	bytes: number
	cache?: string
}

/** Starts request timing only when `AJO_TIMING` enables diagnostics. */
export const start = (): Timing | undefined =>
	timed() ? { start: performance.now() } : undefined

/** Measures monotonic elapsed milliseconds rounded to one decimal place. */
export const elapsed = (start: number) => round(performance.now() - start)

/** Completes started timing state with the response outcome. */
export const finish = (
	timing: Timing,
	result: Omit<Result, keyof Timing | 'total'>,
): Result => ({
	...timing,
	...result,
	total: elapsed(timing.start),
})

/** Formats server phase durations for the standard `Server-Timing` header. */
export const header = (result: Result) => [
	`total;dur=${result.total}`,
	result.loader !== undefined && `loader;dur=${result.loader}`,
	result.render !== undefined && `render;dur=${result.render}`,
].filter(Boolean).join(', ')

/** Writes one compact request timing record to the process log. */
export const log = (label: string, result: Result) => {
	const cache = result.cache ? ` ${result.cache}` : ''
	const loader = result.loader === undefined ? '-' : `${result.loader}ms`
	const render = result.render === undefined ? '-' : `${result.render}ms`
	console.log(`[ajo] ${label} ${result.status}${cache} total=${result.total}ms loader=${loader} render=${render} bytes=${result.bytes}`)
}
